export const TRANSLATIONS = {
  'en-US': {
    update_required: 'Please update your client version',
    wait_update:
      'Your client version is higher than the server version, please wait for the server to update',
    version_to_polyfill:
      'Your client version is not fully supported. Please rejoin to enable temporary compatibility mode. For the best experience, we recommend updating your game to the latest version.',
    version_polyfilled:
      'Temporary compatibility mode has been enabled for your version. We recommend updating your game to avoid potential compatibility issues in the future.',
    bad_user_name: 'Please enter the correct ID',
    blank_room_name: 'Blank room name is unallowed, please fill in something.',
    replay_hint_part1: 'Sending the replay of the duel number ',
    replay_hint_part2: '.',
    watch_join: 'joined as spectator.',
    quit_watch: 'quited spectating',
    left_game: 'quited game',
    disconnect_from_game: 'disconnected from the game',
    reconnect_to_game: 'reconnected to the game',
    reconnect_kicked:
      "You are kicked out because you're logged in on other devices.",
    windbot_deck_not_found: 'Oops, AI or Deck not found',
    windbot_name_too_long:
      'Error occurs, please create a new game and enter /ai to summon an AI.',
    create_room_failed: 'Game creation failed, please try again later.',
    invalid_password_not_found: 'Password invalid (Not Found)',
    add_windbot_failed: 'AI addition failed, enter /ai again.',
    pre_reconnecting_to_room:
      'You will be reconnected to your previous game. Please pick your previous deck.',
    deck_incorrect_reconnect: 'Please pick your previous deck.',
    reconnect_failed: 'Reconnect failed.',
    reconnecting_to_room: 'Reconnecting to server...',
    side_timeout_part1: 'Changing side time is limited to ',
    side_timeout_part2: ' minutes.',
    side_remain_part1: 'Remaining side changing time: ',
    side_remain_part2: ' minutes.',
    side_overtime: 'You exceeded side changing time and were kicked by system.',
    side_overtime_room: ' exceeded side changing time and was kicked by system.',
  },
  'zh-CN': {
    update_required: '请更新你的客户端版本',
    wait_update: '你的客户端版本高于服务器版本，请等待服务器更新',
    version_to_polyfill:
      '当前客户端版本暂未完全支持。请重新加入以启用临时兼容模式。为获得更佳体验，建议尽快更新游戏版本。',
    version_polyfilled:
      '已为当前版本启用临时兼容模式。建议尽快更新游戏，以避免后续兼容性问题。',
    bad_user_name: '请输入正确的用户名',
    blank_room_name: '房间名不能为空，请在主机密码处填写房间名',
    replay_hint_part1: '正在发送第',
    replay_hint_part2: '局决斗的录像。',
    watch_join: '加入了观战',
    quit_watch: '退出了观战',
    left_game: '离开了游戏',
    disconnect_from_game: '断开了连接',
    reconnect_to_game: '重新连接了',
    reconnect_kicked: '你的账号已经在其他设备登录，你被迫下线。',
    windbot_deck_not_found: '未找到该AI角色或卡组',
    windbot_name_too_long: 'AI房间名过长，请在建立房间后输入 /ai 来添加AI',
    create_room_failed: '建立房间失败，请重试',
    invalid_password_not_found: '主机密码不正确 (Not Found)',
    add_windbot_failed: '添加AI失败，可尝试输入 /ai 重新添加',
    pre_reconnecting_to_room:
      '你有未完成的对局，即将重新连接，请选择你在本局决斗中使用的卡组并准备。',
    deck_incorrect_reconnect: '请选择你在本局决斗中使用的卡组。',
    reconnect_failed: '重新连接失败。',
    reconnecting_to_room: '正在重新连接到服务器……',
    side_timeout_part1: '你现在有',
    side_timeout_part2: '分钟来更换副卡组。',
    side_remain_part1: '更换副卡组剩余时间：',
    side_remain_part2: '分钟。',
    side_overtime: '你更换副卡组超时，已被系统踢出。',
    side_overtime_room: '更换副卡组超时，已被系统踢出。',
  },
};
