export const TRANSLATIONS = {
  'en-US': {
    update_required: 'Please update your client version',
    wait_update:
      'Your client version is higher than the server version, please wait for the server to update',
    version_to_polyfill:
      'Your client version is not fully supported. Please rejoin to enable temporary compatibility mode. For the best experience, we recommend updating your game to the latest version.',
    version_polyfilled:
      'Temporary compatibility mode has been enabled for your version. We recommend updating your game to avoid potential compatibility issues in the future.',
    bad_user_name: 'Please enter the correct ID',
    bad_name_level1: 'Your username contains blocked words.',
    bad_name_level2: 'Your username contains blocked words.',
    bad_name_level3: 'Your username contains blocked words.',
    bad_roomname_level1: 'Your room name contains blocked words.',
    bad_roomname_level2: 'Your room name contains blocked words.',
    bad_roomname_level3: 'Your room name contains blocked words.',
    blank_room_name: 'Blank room name is unallowed, please fill in something.',
    replay_hint_part1: 'Sending the replay of the duel number ',
    replay_hint_part2: '.',
    watch_join: 'joined as spectator.',
    quit_watch: 'quited spectating',
    left_game: 'quited game',
    disconnect_from_game: 'disconnected from the game',
    reconnect_to_game: 'reconnected to the game',
    reconnect_kicked:
      "You are kicked out because you're logged in on other devices.",
    windbot_deck_not_found: 'Oops, AI or Deck not found',
    windbot_name_too_long:
      'Error occurs, please create a new game and enter /ai to summon an AI.',
    create_room_failed: 'Game creation failed, please try again later.',
    invalid_password_not_found: 'Password invalid (Not Found)',
    banned_ip_login: 'You have been banned.',
    banned_user_login: 'You have been banned.',
    add_windbot_failed: 'AI addition failed, enter /ai again.',
    pre_reconnecting_to_room:
      'You will be reconnected to your previous game. Please pick your previous deck.',
    deck_incorrect_reconnect: 'Please pick your previous deck.',
    deck_correct_part1: 'Your deck ',
    deck_correct_part2: ' has passed the deck check for this tournament.',
    deck_incorrect_part1:
      'The deck you are using is not the same as your submitted deck ',
    deck_incorrect_part2:
      ' . Please make sure all the cards are in the correct sequence.',
    deck_not_found:
      ', we did not receive your registration. Please make sure you are using the correct ID for the tournament.',
    reconnect_failed: 'Reconnect failed.',
    reconnecting_to_room: 'Reconnecting to server...',
    side_timeout_part1: 'Changing side time is limited to ',
    side_timeout_part2: ' minutes.',
    side_remain_part1: 'Remaining side changing time: ',
    side_remain_part2: ' minutes.',
    side_overtime: 'You exceeded side changing time and were kicked by system.',
    side_overtime_room:
      ' exceeded side changing time and was kicked by system.',
    kicked_by_system: 'was evicted from the game by server.',
    kick_count_down:
      ' seconds later this player will be evicted for not getting ready or starting the game.',
    afk_warn_part1: 'no operation too long, will be disconnected after ',
    afk_warn_part2: ' seconds',
    random_duel_enter_room_waiting: 'Your opponent is ready, start now!',
    random_duel_enter_room_new: 'Game created, waiting for random opponent.',
    random_duel_enter_room_single:
      'Single mode room. Password M for match mode, T for tag mode.',
    random_duel_enter_room_match:
      'Match mode room. Password S for single mode, T for tag mode.',
    random_duel_enter_room_tag:
      'Tag mode room. Password S for single mode, M for match mode.',
    random_banned_part1: 'You have been banned from the game due to ',
    random_banned_part2: ', it will last until ',
    random_banned_part3: '.',
    random_deprecated_part1: 'Because of your ',
    random_deprecated_part2:
      ', in recent games, you will only suffer other players who are under same punishment as you in ',
    random_deprecated_part3: '.',
    random_warn_part1: 'The system detects that recently you had ',
    random_warn_part2:
      ' in recent games, you will be penalized after 3 offences',
    random_ban_reason_separator: '/',
    random_ban_reason_flee: 'Flee',
    random_ban_reason_AFK: 'AFK',
    random_ban_reason_abuse: 'Abusing',
    random_ban_reason_zombie: 'Zombie',
    random_score_part1: 'Record of ',
    random_score_part2: ': ',
    random_score_part3: '% WIN, ',
    random_score_part4_combo: '% RAGE QUIT, WIN COMBO ',
    random_score_part5_combo: ' !',
    random_score_part4: '%',
    random_score_blank: " didn't have enough duel record.",
    random_score_not_enough: " didn't have enough duel record.",
    unwelcome_warn_part1: 'If you keep doing ',
    unwelcome_warn_part2: ', your opponent may leave you.',
    unwelcome_tip_part1: 'Your opponent did ',
    unwelcome_tip_part2: ', so you can leave the game without being punished.',
    banned_duel_tip:
      'You are banned from the random duel system for sending inappropriate messages.',
    chat_banned: 'is banned from chat.',
    surrender_denied: "Please don't surrender in the first 2 turns.",
    room_name: 'Room name is',
    refresh_success: 'Refresh field succeeded.',
    refresh_fail: 'Refresh field failed.',
    chat_disabled: 'Chat is disabled in this room.',
    chat_warn_level1: 'Please avoid sensitive words.',
    chat_warn_level2: 'Your message contains blocked words.',
    menu_random_duel: 'Random Duel',
    menu_random_duel_match: 'Random Duel (Match)',
    menu_ai_duel: 'AI Duel',
    menu_more: 'More',
    menu_random_duel_single: 'Random Duel (Single)',
    menu_random_duel_tag: 'Random Duel (Tag)',
    menu_ai_duel_match: 'AI Duel (Match)',
    menu_ai_duel_tag: 'AI Duel (Tag)',
    menu_return: 'Return',
    menu_match_random_duel: 'Match Random Duel',
    menu_single_random_duel: 'Single Random Duel',
    menu_prev_page: 'Previous Page',
    menu_next_page: 'Next Page',
    koishi_cmd_tip_desc: 'Send a random tip.',
    koishi_cmd_ai_desc: 'Add windbot to current room.',
    koishi_cmd_surrender_desc: 'Surrender current duel.',
    koishi_cmd_roomname_desc: 'Show current room name.',
    koishi_cmd_refresh_desc: 'Refresh duel field state.',
    koishi_cmd_ip_desc: 'Show your current IP.',
    koishi_ai_only_host: 'Only room host can use /ai.',
    koishi_ai_disabled: 'Windbot feature is disabled.',
    koishi_ai_disabled_random_room: 'AI is disabled in random duel rooms.',
    koishi_ai_room_full: 'Room is full, cannot add AI.',
    cloud_replay_no: 'Replay not found.',
    cloud_replay_error: 'Replay opening failed.',
    cloud_replay_playing: 'Accessing cloud replay',
    cloud_replay_hint:
      'These are your recent cloud replays. Select one from the menu to continue.',
    cloud_replay_detail_time: 'Time: ',
    cloud_replay_detail_players: 'Duel: ',
    cloud_replay_detail_score: 'Score: ',
    cloud_replay_detail_winner: 'Winner: ',
    cloud_replay_detail_access_hint_part1: 'Host Password: enter ',
    cloud_replay_detail_access_hint_part2: ' to access this replay.',
    cloud_replay_menu_play: 'Play Cloud Replay',
    cloud_replay_menu_download_yrp: 'Download YRP Replay',
    cloud_replay_menu_back: 'Back',
    death_cancel: 'Over-match has been canceled from this game.',
    death_start:
      'Over-time match has begun, player with higher LP will win the single game after 4 turns.',
    death_start_siding:
      'Extra time match starts, player with higher LP will win the single game after 4 turns.',
    death_start_final:
      'You are getting into sudden-death match, the Duel continues until the first change in LP happens.',
    death_start_extra:
      'The Duel is counted as extra duel which will end in 4 turns, player with higher LP will win.',
    death_remain_part1: 'The Duel will be ended in ',
    death_remain_part2:
      ' turns. At the end of that turn, player with higher LP wins.',
    death_remain_final:
      'The Duel will continue until the first change in LP (and increase or a decrease), and at the end of the turn, the player with the highest LP total becomes the winner.',
    death_finish_part1: 'Extra time duel ends, congratulations. ',
    death_finish_part2: ', You win the Duel.',
    death2_finish_part1: 'Extra time match ends, congratulations. ',
    death2_finish_part2: ', You win the Match.',
    lp_low_opponent: 'もはやお前のライフは風前の灯！',
    lp_low_self: '*Low LP Alert*',
    botlist_menu_single: 'Single',
    botlist_menu_match: 'Match',
    botlist_menu_back: 'Back',
  },
  'zh-CN': {
    update_required: '请更新你的客户端版本',
    wait_update: '你的客户端版本高于服务器版本，请等待服务器更新',
    version_to_polyfill:
      '当前客户端版本暂未完全支持。请重新加入以启用临时兼容模式。为获得更佳体验，建议尽快更新游戏版本。',
    version_polyfilled:
      '已为当前版本启用临时兼容模式。建议尽快更新游戏，以避免后续兼容性问题。',
    bad_user_name: '请输入正确的用户名',
    bad_name_level1: '你的用户名包含敏感词，请修改后重试。',
    bad_name_level2: '你的用户名包含敏感词，请修改后重试。',
    bad_name_level3: '你的用户名包含敏感词，请修改后重试。',
    bad_roomname_level1: '房间名包含敏感词，请修改后重试。',
    bad_roomname_level2: '房间名包含敏感词，请修改后重试。',
    bad_roomname_level3: '房间名包含敏感词，请修改后重试。',
    blank_room_name: '房间名不能为空，请在主机密码处填写房间名',
    replay_hint_part1: '正在发送第',
    replay_hint_part2: '局决斗的录像。',
    watch_join: '加入了观战',
    quit_watch: '退出了观战',
    left_game: '离开了游戏',
    disconnect_from_game: '断开了连接',
    reconnect_to_game: '重新连接了',
    reconnect_kicked: '你的账号已经在其他设备登录，你被迫下线。',
    windbot_deck_not_found: '未找到该AI角色或卡组',
    windbot_name_too_long: 'AI房间名过长，请在建立房间后输入 /ai 来添加AI',
    create_room_failed: '建立房间失败，请重试',
    invalid_password_not_found: '主机密码不正确 (Not Found)',
    banned_ip_login:
      '您的账号已被封禁。如果您没有进行违规操作且用的是流量网络，可能过几小时就好。是IP撞了。',
    banned_user_login:
      '您的账号已被封禁。如果您没有进行违规操作且用的是流量网络，可能过几小时就好。是IP撞了。',
    add_windbot_failed: '添加AI失败，可尝试输入 /ai 重新添加',
    pre_reconnecting_to_room:
      '你有未完成的对局，即将重新连接，请选择你在本局决斗中使用的卡组并准备。',
    deck_incorrect_reconnect: '请选择你在本局决斗中使用的卡组。',
    deck_correct_part1: '成功使用卡组 ',
    deck_correct_part2: ' 参加比赛。',
    deck_incorrect_part1: '您的卡组与报名卡组 ',
    deck_incorrect_part2: ' 不符。注意卡组不能有包括卡片顺序在内的任何修改。',
    deck_not_found: '，没有找到您的报名信息，请确定您使用昵称与报名ID一致。',
    reconnect_failed: '重新连接失败。',
    reconnecting_to_room: '正在重新连接到服务器……',
    side_timeout_part1: '你现在有',
    side_timeout_part2: '分钟来更换副卡组。',
    side_remain_part1: '更换副卡组剩余时间：',
    side_remain_part2: '分钟。',
    side_overtime: '你更换副卡组超时，已被系统踢出。',
    side_overtime_room: '更换副卡组超时，已被系统踢出。',
    kicked_by_system: '被系统请出了房间',
    kick_count_down: '秒后若不准备或开始游戏将被请出房间',
    afk_warn_part1: '已经很久没有操作了，若继续挂机，将于',
    afk_warn_part2: '秒后被请出房间',
    random_duel_enter_room_waiting: '对手已经在等你了，开始决斗吧！',
    random_duel_enter_room_new: '已建立随机对战房间，正在等待对手！',
    random_duel_enter_room_single:
      '您进入了单局模式房间，密码输入 M 进入比赛模式，输入 T 进入双打模式。',
    random_duel_enter_room_match:
      '您进入了比赛模式房间，密码输入 S 进入单局模式，输入 T 进入双打模式。',
    random_duel_enter_room_tag:
      '您进入了双打模式房间，密码输入 S 进入单局模式，输入 M 进入比赛模式。',
    random_banned_part1: '因为您近期在游戏中多次',
    random_banned_part2: '，您已被禁止使用随机对战功能，将在',
    random_banned_part3: '后解封',
    random_deprecated_part1: '因为您近期在游戏中',
    random_deprecated_part2: '，在',
    random_deprecated_part3: '内您随机对战时只能遇到其他违规玩家。',
    random_warn_part1: '系统检测到您近期在游戏中',
    random_warn_part2: '，若您违规超过3次，将受到惩罚',
    random_ban_reason_separator: '、',
    random_ban_reason_flee: '强退',
    random_ban_reason_AFK: '挂机',
    random_ban_reason_abuse: '发言违规',
    random_ban_reason_zombie: '挂房间',
    random_score_part1: '',
    random_score_part2: '的战绩：胜率',
    random_score_part3: '%，逃跑率',
    random_score_part4_combo: '%，',
    random_score_part5_combo: '连胜中！',
    random_score_part4: '%',
    random_score_blank: '的战绩：正在统计中',
    random_score_not_enough: '的战绩：正在统计中',
    unwelcome_warn_part1: '如果您经常',
    unwelcome_warn_part2: '，您的对手可能会离你而去。',
    unwelcome_tip_part1: '因为您的对手有',
    unwelcome_tip_part2: '行为，现在您可以直接离开游戏或投降，不视为强退。',
    banned_duel_tip: '您的发言存在严重不适当的内容，禁止您使用随机对战功能！',
    chat_banned: '已被禁言！',
    surrender_denied: '为保证双方玩家的游戏体验，随机对战中3回合后才能投降。',
    room_name: '您当前的房间名是',
    refresh_success: '刷新场面成功。',
    refresh_fail: '刷新场面失败。',
    chat_disabled: '本房间禁止聊天。',
    chat_warn_level1: '请注意发言，敏感词已被替换。',
    chat_warn_level2: '消息包含敏感词，已被拦截。',
    menu_random_duel: '随机对战',
    menu_random_duel_match: '随机对战（比赛）',
    menu_ai_duel: '人机对战',
    menu_more: '更多',
    menu_random_duel_single: '随机对战（单局）',
    menu_random_duel_tag: '随机对战（双打）',
    menu_ai_duel_match: '人机对战（比赛）',
    menu_ai_duel_tag: '人机对战（双打）',
    menu_return: '返回',
    menu_match_random_duel: '随机对战（比赛）',
    menu_single_random_duel: '随机对战（单局）',
    menu_prev_page: '上一页',
    menu_next_page: '下一页',
    koishi_cmd_tip_desc: '发送一条随机提示。',
    koishi_cmd_ai_desc: '为当前房间添加AI。',
    koishi_cmd_surrender_desc: '投降当前对局。',
    koishi_cmd_roomname_desc: '显示当前房间名。',
    koishi_cmd_refresh_desc: '刷新当前场面信息。',
    koishi_cmd_ip_desc: '显示当前 IP。',
    koishi_ai_only_host: '只有房主可以使用 /ai。',
    koishi_ai_disabled: '人机功能未开启。',
    koishi_ai_disabled_random_room: '随机对战房间不允许使用 /ai。',
    koishi_ai_room_full: '房间已满，无法添加AI。',
    cloud_replay_no: '没有找到录像',
    cloud_replay_error: '播放录像出错',
    cloud_replay_playing: '正在观看云录像',
    cloud_replay_hint: '以下是您近期的云录像，请在菜单中选择一条继续。',
    cloud_replay_detail_time: '时间：',
    cloud_replay_detail_players: '对局：',
    cloud_replay_detail_score: '比分：',
    cloud_replay_detail_winner: '胜者：',
    cloud_replay_detail_access_hint_part1: '主机密码输入 ',
    cloud_replay_detail_access_hint_part2: ' 即可访问本录像。',
    cloud_replay_menu_play: '播放云录像',
    cloud_replay_menu_download_yrp: '下载 YRP 录像',
    cloud_replay_menu_back: '返回',
    death_cancel: '已取消本房间的加时赛状态。',
    death_start: '加时赛开始，从本回合开始计算4回合，基本分高的玩家获得本次决斗的胜利。',
    death_start_siding: '加时赛开始，下次决斗的第4回合结束时，基本分高的玩家决斗胜利。',
    death_start_final:
      '本次决斗将进入猝死赛，基本分发生变动的回合结束时，基本分高的玩家将获得本次决斗的胜利。',
    death_start_extra:
      '本次决斗为额外决斗，第4回合结束时，基本分高的玩家获得本次决斗的胜利。',
    death_remain_part1: '本次决斗将在',
    death_remain_part2: '回合后结束，基本分高的玩家将获得本次决斗的胜利。',
    death_remain_final:
      '若本回合基本分发生变动，在该回合结束时决斗即告结束，基本分高的玩家获得本场决斗的胜利。',
    death_finish_part1: '加时赛决斗结束，恭喜 ',
    death_finish_part2: ' 获得本次决斗的胜利。',
    death2_finish_part1: '加时赛结束，恭喜 ',
    death2_finish_part2: ' 获得本次比赛的胜利。',
    lp_low_opponent: '你的生命已经如风中残烛了！',
    lp_low_self: '背水一战！',
    botlist_menu_single: '单局',
    botlist_menu_match: '比赛',
    botlist_menu_back: '返回',
  },
};
